const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_ERROR: 500,
  SERVICE_UNAVAILABLE: 503
};

const ERROR_CODES = {
  INVALID_CREDENTIALS: 'AUTH_001',
  TOKEN_EXPIRED: 'AUTH_002',
  TOKEN_INVALID: 'AUTH_003',
  USER_NOT_FOUND: 'USER_001',
  FORBIDDEN: 'FORBIDDEN_001',
  INVALID_INPUT: 'VALIDATION_001',
  DATABASE_ERROR: 'DB_001',
  NOT_FOUND: 'NOT_FOUND_001',
  INTERNAL_ERROR: 'INTERNAL_001'
};

const ROLES = {
  ADMIN: 'ADMIN',
  TEACHER: 'TEACHER',
  PARENT: 'PARENT',
  STUDENT: 'STUDENT'
};

module.exports = {
  HTTP_STATUS,
  ERROR_CODES,
  ROLES
};
